# Generated by Django 4.2 on 2024-03-07 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 7, 7, 35, 43, 684767, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='school',
            name='foundation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 7, 35, 43, 677060, tzinfo=datetime.timezone.utc)),
        ),
    ]
